version: "2"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    container_name: kibana    
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.3
    container_name: logstash
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    